jwt:
  signing-key: "I0AjQFJAdiEmQW5rIVQkfC18XnJtQA=="
  authorities-key: roles
  header-key: Authorization
  token:
    prefix: Bearer
    validity: 4800

logging.level:
  root: DEBUG

spring:
  datasource:
    embedded-database-connection: h2
    password: test
    username: test
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true