CREATE TABLE IF NOT EXISTS USER_ENTITY
(
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME   VARCHAR(100),
    LAST_NAME    VARCHAR(100),
    PHONE        VARCHAR(20),
    EMAIL        VARCHAR(20),
    PASSWORD     VARCHAR(100),
    CREATED_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ROLE
(
    NAME        VARCHAR(20),
    USER_ENTITY BIGINT REFERENCES USER_ENTITY (ID)
);