CREATE TABLE IF NOT EXISTS USER_ENTITY
(
    ID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME       VARCHAR(100),
    LAST_NAME        VARCHAR(100),
    PHONE            VARCHAR(20),
    EMAIL            VARCHAR(20),
    PASSWORD         VARCHAR(100),
    ROLES            VARCHAR[],
    CREATED_DATE     TIMESTAMP,
    STATUS           VARCHAR(20),
    ACTIVATED        BOOLEAN,
    ACTIVATION_KEY   VARCHAR(100),
    CREATED_BY       BIGINT,
    LAST_MODIFIED_BY BIGINT
);